import "./globals.css";
import Logo from "../components/Logo";
import Header from "../components/Header";
import React from "react";

export const metadata = {
  title: "BuyPass",
  description: "Generated by create next app",
};

const rainforestKey = process.env.NEXT_PUBLIC_RAINFOREST_KEY;
const baseURL = `https://api.rainforestapi.com/request?`;
const amazon_domain = `amazon.com`;

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Logo />
        <Header />
        {children}
      </body>
    </html>
  );
}
