import "./globals.css";

export const metadata = {
  title: "BuyPass",
  description: "Generated by create next app",
  // icons: [
  //   { rel: "icon", type: "image/png", sizes: "32x32", url: "./favicon.ico" },
  // ],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="p-0 m-0 border-box scroll-smooth">
      {/* <Head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </Head> */}
      <body className="h-[100vh]">{children}</body>
    </html>
  );
}
