import "./globals.css";
import "dotenv/config";
import Logo from "../components/Logo";
import Header from "../components/Header";
import React from "react";

export const metadata = {
  title: "BuyPass",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Logo />
        <Header />
        {children}
      </body>
    </html>
  );
}
